name: Deploy to ACR

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  IMAGE_NAME: luciebottin/iris-docker
  ACR_NAME: acr-iris-docker
  RESOURCE_GROUP: iris-group5

jobs:
  build:
    name: Build container image
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker CLI
        uses: actions/docker/cli@v2
        with:
          context: .
    
      - name: Build the Docker image
        run: |
          docker build -t $(env.IMAGE_NAME) .
      - name: Login to ACR
        run: |
          az acr login --name $(env.ACR_NAME)
      - name: Deploy the Docker image to ACR
        run: |
          docker push $(env.ACR_NAME)/$(env.IMAGE_NAME)
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Get tag
        id: tag
        uses: dawidd6/action-get-tag@v1
      - name: Log into registry
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.ACR_ENDPOINT }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
      - name: Build & Push
        uses: docker/build-push-action@v2
        with:
          python-version: 3.8
          push: true
          build-args: |
            version=${{ steps.tag.outputs.tag }}
          tags: ${{ secrets.ACR_ENDPOINT }}/${{ env.IMAGE_NAME }}:${{ steps.tag.outputs.tag }}
          
