name: Deploy to ACR

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build container image
    runs-on: windows-latest
    steps: 
      - name: Login to Azure
        run: |
          az login 
      - name: Login to ACR
        run: |
          az acr login --name ${{ secrets.ACR_NAME }}
      - name: Login to ACR 2
        uses: azure/docker-login@v1
        with: 
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
      - name: Build the Docker image
        run: |
          docker build -t ${{ secrets.IMAGE_NAME }}:latest .
      - name: Deploy the Docker image to ACR
        run: |
          docker push ${{ secrets.ACR_NAME }}/${{ secrets.IMAGE_NAME }}
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Get tag
        id: latest
        uses: dawidd6/action-get-tag@v1
      - name: Log into registry
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.ACR_ENDPOINT }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
      - name: Build & Push
        uses: docker/build-push-action@v2
        with:
          python-version: 3.8
          push: true
          build-args: |
            version=${{ steps.tag.outputs.tag }}
          tags: ${{ secrets.ACR_ENDPOINT }}/${{ env.IMAGE_NAME }}:${{ steps.tag.outputs.tag }}
          
